spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

security:
  jwt:
    token:
      secret-key: prod-secret